name: simpelbudget
description: "Simpelbudget is a budget tracking app that helps you keep track of your expenses and incomes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  generate: true
